name: Test Package

on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:

jobs:
  build:
    name: Test Package
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - run: pip install pytest
      - run: pip install .
      - run: pytest
